--!strict
local Server = game.ServerScriptService.Server
local types = Server.Types
local config = Server.Config

local restaurantObjectTypes = require(types.RestaurantObjectTypes)
local info = require(config.Info)

local Config : {[string] : restaurantObjectTypes.TableDecor} = {
	as_dec_table_1 = {
		name = 'Перо аиста',
		price = 800,
		interior = 50,
		image = "rbxassetid://17804941493",
		level = 1,
		-- layoutOrder = 1,
		country = info.COUNTRY.panasia,
	},	
	as_dec_table_2 = {
		name = 'Громовой змей',
		price = 800,
		interior = 50,
		image = "rbxassetid://17804941312",
		level = 1,
		-- layoutOrder = 3,
		country = info.COUNTRY.panasia,
	},	
	as_dec_table_3 = {
		name = 'Взгляд осени',
		price = 800,
		interior = 50,
		image = "rbxassetid://17804941159",
		level = 1,
		-- layoutOrder = 5,
		country = info.COUNTRY.panasia,
	},	
	--as_dec_table_4 = {
	--	name = 'Глаз солнца',
	--	price = 800,
	--	interior = 100,
	--	image = "rbxassetid://17804940989",
	--	level = 1,
		-- layoutOrder = 7,
	--	country = info.COUNTRY.panasia,
	--},
	eu_dec_table_1 = {
		name = 'Парящий сокол',
		price = 800,
		interior = 50,
		image = "rbxassetid://17804818940",
		level = 1,
		-- layoutOrder = 8,
		country = info.COUNTRY.europe,
	},
	eu_dec_table_2 = {
		name = 'Орлиный глаз',
		price = 800,
		interior = 50,
		image = "rbxassetid://17804818771",
		level = 1,
		-- layoutOrder = 9,
		country = info.COUNTRY.europe,
	},
	eu_dec_table_3 = {
		name = 'Зов моря',
		price = 800,
		interior = 50,
		image = "rbxassetid://17804818413",
		level = 1,
		-- layoutOrder = 10,
		country = info.COUNTRY.europe,
	},
	ru_dec_table_1 = {
		name = 'Царевна-лебедь',
		price = 800,
		interior = 50,
		image = "rbxassetid://17804910484",
		level = 1,
		-- layoutOrder = 11,
		country = info.COUNTRY.russia,
	},
	ru_dec_table_2 = {
		name = 'Богатырский конь',
		price = 800,
		interior = 50,
		image = "rbxassetid://17804910341",
		level = 1,
		-- layoutOrder = 12,
		country = info.COUNTRY.russia,
	},
	ru_dec_table_3 = {
		name = 'Хозяин застолья',
		price = 800,
		interior = 50,
		image = "rbxassetid://17804910151",
		level = 1,
		-- layoutOrder = 13,
		country = info.COUNTRY.russia,
	},
	it_dec_table_1 = {
		name = 'Пламя свободы',
		price = 800,
		interior = 50,
		image = "rbxassetid://17804862239",
		level = 1,
		-- layoutOrder = 14,
		country = info.COUNTRY.italy,
	},
	it_dec_table_2 = {
		name = 'Зеленый уют',
		price = 800,
		interior = 50,
		image = "rbxassetid://17804862104",
		level = 1,
		-- layoutOrder = 15,
		country = info.COUNTRY.italy,
	},
	it_dec_table_3 = {
		name = 'Мягкий свет',
		price = 800,
		interior = 50,
		image = "rbxassetid://17804861964",
		level = 1,
		-- layoutOrder = 16,
		country = info.COUNTRY.italy,
	},
	ca_dec_table_1 = {
		name = 'Идеальная форма',
		price = 800,
		interior = 50,
		image = "rbxassetid://17804771378",
		level = 1,
		-- layoutOrder = 17,
		country = info.COUNTRY.caucasus,
	},
	ca_dec_table_2 = {
		name = 'Вкусный стол',
		price = 800,
		interior = 50,
		image = "rbxassetid://17804771180",
		level = 1,
		-- layoutOrder = 18,
		country = info.COUNTRY.caucasus,
	},
	ca_dec_table_3 = {
		name = 'Кислинка',
		price = 800,
		interior = 50,
		image = "rbxassetid://17804770977",
		level = 1,
		-- layoutOrder = 19,
		country = info.COUNTRY.caucasus,
	}
}

return Config
